plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'main.Main'
    tasks.named('run') {
        standardInput = System.in
    }
}

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(25)
    }
}

dependencies {
    implementation 'org.slf4j:slf4j-api:2.0.16'
    implementation 'org.slf4j:slf4j-simple:2.0.16'

    testImplementation 'org.testng:testng:7.10.2'
}

test {
    useTestNG()
}